# Generated by Django 5.2.10 on 2026-01-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custo',
                'verbose_name_plural': 'Custos',
            },
        ),
        migrations.CreateModel(
            name='Justificativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=150)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_desativa', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Justificativa',
                'verbose_name_plural': 'Justificativas',
            },
        ),
        migrations.CreateModel(
            name='Margem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margem_bruta', models.DecimalField(decimal_places=2, max_digits=18)),
                ('margem_bruta_percentual', models.DecimalField(decimal_places=4, max_digits=18)),
            ],
            options={
                'verbose_name': 'Margem',
                'verbose_name_plural': 'Margens',
            },
        ),
        migrations.CreateModel(
            name='Nf_Has_Justificativa',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('chave', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('filial', models.CharField(default=None, max_length=50)),
                ('nota', models.CharField(default=None, max_length=20)),
                ('no_pedido', models.CharField(default=None, max_length=15)),
                ('vendedor', models.CharField(default=None, max_length=60, null=True)),
                ('data_emissao', models.DateField()),
                ('lote', models.CharField(default=None, max_length=20)),
                ('cfop', models.CharField(default=None, max_length=6)),
                ('cfop_descri', models.CharField(default=None, max_length=60)),
                ('atualiza_estoque', models.CharField(default=None, max_length=1)),
                ('gera_duplicata', models.CharField(default=None, max_length=1)),
                ('cod_produto', models.CharField(default=None, max_length=15)),
                ('produto', models.CharField(default=None, max_length=50)),
                ('tipo_produto', models.CharField(default=None, max_length=2)),
                ('armazem', models.CharField(default=None, max_length=60)),
                ('cod_cliente', models.CharField(default=None, max_length=10)),
                ('loja', models.CharField(default=None, max_length=4)),
                ('cliente', models.CharField(default=None, max_length=100)),
                ('grp_amar_ctb', models.CharField(default=None, max_length=10)),
                ('classificacao_produto', models.CharField(default=None, max_length=100, null=True)),
                ('estado_destino', models.CharField(default=None, max_length=2)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_contabil', models.DecimalField(decimal_places=2, max_digits=18)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=18)),
                ('valor_ipi', models.DecimalField(decimal_places=2, max_digits=18)),
                ('valor_imp5', models.DecimalField(decimal_places=2, max_digits=18)),
                ('valor_imp6', models.DecimalField(decimal_places=2, max_digits=18)),
                ('valor_icms_difal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('valor_icms', models.DecimalField(decimal_places=2, max_digits=18)),
                ('aliq_icms', models.DecimalField(decimal_places=2, max_digits=5)),
                ('delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
    ]
