# Generated by Django 5.2.10 on 2026-01-30 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='custo',
            name='usuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='justificativa',
            name='usuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='margem',
            name='custo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notas.custo'),
        ),
        migrations.AddField(
            model_name='nf_has_justificativa',
            name='justificativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notas.justificativa'),
        ),
        migrations.AddField(
            model_name='nf_has_justificativa',
            name='usuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nf_has_justificativa',
            name='nf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notas.nota'),
        ),
        migrations.AddField(
            model_name='margem',
            name='chave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notas.nota'),
        ),
        migrations.AddField(
            model_name='custo',
            name='chave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notas.nota'),
        ),
    ]
