# Generated by Django 5.2.10 on 2026-01-30 12:08

from django.db import migrations
from notas.models import Justificativa

def criar_justificativas_padrao(apps, schema_editor):
    Justificativa.objects.bulk_create([
        Justificativa(texto='Limpar / Sem Justificativa'),
        Justificativa(texto='OK. Margem Parceiro.'),
        Justificativa(texto='Tabela de Preço Errada'),
        Justificativa(texto='Refaturado com Valor Correto'),
        Justificativa(texto='Desconto aplicado para concluir a venda'),
        Justificativa(texto='Venda Cancelada'),
    ])
    
class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_initial'),
        ('users', '0002_auto_20260130_0903'),
    ]

    operations = [
        migrations.RunPython(criar_justificativas_padrao)
    ]
