# Generated by Django 5.2.10 on 2026-01-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_auto_20260130_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nf_has_justificativa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
