# Generated by Django 5.2.10 on 2026-02-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0004_alter_nf_has_justificativa_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='nome_filial',
            field=models.CharField(default=None, max_length=80),
        ),
    ]
