# Generated by Django 5.2.10 on 2026-03-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0005_nota_nome_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='desc_tipo_produto',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
