# Generated by Django 5.2.10 on 2026-03-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0006_nota_desc_tipo_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='OP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(default=None, max_length=50)),
                ('produto', models.CharField(default=None, max_length=15)),
                ('armazem', models.CharField(default=None, max_length=60)),
                ('tp_movimento', models.CharField(default=None, max_length=3)),
                ('descricao_tm', models.CharField(default=None, max_length=50)),
                ('descr_prod', models.CharField(default=None, max_length=50)),
                ('unidade', models.CharField(default=None, max_length=2)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quant_2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=18)),
                ('custo_2', models.DecimalField(decimal_places=2, max_digits=18)),
                ('ord_producao', models.CharField(default=None, max_length=12)),
                ('lote', models.CharField(default=None, max_length=20)),
                ('os_ass_tecn', models.CharField(default=None, max_length=8)),
                ('grupo', models.CharField(default=None, max_length=4)),
                ('descricao_grupo', models.CharField(default=None, max_length=60)),
                ('tipo_re_de', models.CharField(default=None, max_length=3)),
                ('ext_texto', models.CharField(default=None, max_length=2)),
                ('documento', models.CharField(default=None, max_length=12)),
                ('dt_emissao', models.DateField()),
                ('c_contabil', models.CharField(default=None, max_length=10)),
                ('descricao_da_conta', models.CharField(default=None, max_length=60)),
                ('centro_custo', models.CharField(default=None, max_length=8)),
                ('desc_centro_de_custo', models.CharField(default=None, max_length=60)),
                ('parc_total', models.CharField(default=None, max_length=1)),
                ('estornado', models.CharField(default=None, max_length=1)),
                ('sequencial', models.CharField(default=None, max_length=6)),
                ('tipo', models.CharField(default=None, max_length=2)),
                ('usuario', models.CharField(default=None, max_length=40)),
                ('nr_s_a', models.CharField(default=None, max_length=6)),
                ('item_s_a', models.CharField(default=None, max_length=2)),
            ],
            options={
                'verbose_name': 'Op',
                'verbose_name_plural': 'Ops',
            },
        ),
    ]
