# Generated by Django 5.2.10 on 2026-03-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0007_op'),
    ]

    operations = [
        migrations.AlterField(
            model_name='op',
            name='armazem',
            field=models.CharField(blank=True, default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='op',
            name='c_contabil',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='op',
            name='centro_custo',
            field=models.CharField(blank=True, default=None, max_length=8),
        ),
        migrations.AlterField(
            model_name='op',
            name='desc_centro_de_custo',
            field=models.CharField(blank=True, default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='op',
            name='descr_prod',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='op',
            name='descricao_da_conta',
            field=models.CharField(blank=True, default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='op',
            name='descricao_grupo',
            field=models.CharField(blank=True, default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='op',
            name='descricao_tm',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='op',
            name='documento',
            field=models.CharField(blank=True, default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name='op',
            name='estornado',
            field=models.CharField(blank=True, default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='op',
            name='ext_texto',
            field=models.CharField(blank=True, default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='op',
            name='filial',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='op',
            name='grupo',
            field=models.CharField(blank=True, default=None, max_length=4),
        ),
        migrations.AlterField(
            model_name='op',
            name='item_s_a',
            field=models.CharField(blank=True, default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='op',
            name='lote',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='op',
            name='nr_s_a',
            field=models.CharField(blank=True, default=None, max_length=6),
        ),
        migrations.AlterField(
            model_name='op',
            name='ord_producao',
            field=models.CharField(blank=True, default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name='op',
            name='os_ass_tecn',
            field=models.CharField(blank=True, default=None, max_length=8),
        ),
        migrations.AlterField(
            model_name='op',
            name='parc_total',
            field=models.CharField(blank=True, default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='op',
            name='produto',
            field=models.CharField(blank=True, default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='op',
            name='sequencial',
            field=models.CharField(blank=True, default=None, max_length=6),
        ),
        migrations.AlterField(
            model_name='op',
            name='tipo',
            field=models.CharField(blank=True, default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='op',
            name='tipo_re_de',
            field=models.CharField(blank=True, default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='op',
            name='tp_movimento',
            field=models.CharField(blank=True, default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='op',
            name='unidade',
            field=models.CharField(blank=True, default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='op',
            name='usuario',
            field=models.CharField(blank=True, default=None, max_length=40),
        ),
    ]
