# Generated by Django 5.2.10 on 2026-03-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0008_alter_op_armazem_alter_op_c_contabil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='preco_tabela',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='nota',
            name='tabela_preco',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
