# Generated by Django 5.2.10 on 2026-03-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0009_nota_preco_tabela_nota_tabela_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='preco_tabela',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18),
        ),
    ]
