# Generated by Django 5.2.10 on 2026-03-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0010_alter_nota_preco_tabela'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='item',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='op',
            name='id_op',
            field=models.CharField(blank=True, default=None, max_length=80),
        ),
        migrations.AlterField(
            model_name='op',
            name='desc_centro_de_custo',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='op',
            name='descr_prod',
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='op',
            name='descricao_da_conta',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='op',
            name='descricao_grupo',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='op',
            name='descricao_tm',
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='op',
            name='documento',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='op',
            name='estornado',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='op',
            name='ext_texto',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='op',
            name='filial',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='op',
            name='item_s_a',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='op',
            name='nr_s_a',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='op',
            name='parc_total',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='op',
            name='produto',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='op',
            name='sequencial',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='op',
            name='tipo',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='op',
            name='tipo_re_de',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='op',
            name='usuario',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
