# Generated by Django 5.2.10 on 2026-03-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0011_nota_item_op_id_op_alter_op_desc_centro_de_custo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='recno',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
