# Generated by Django 5.2.10 on 2026-04-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0013_alter_justificativa_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='tabela_preco',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
