# Generated by Django 5.2.10 on 2026-04-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0014_alter_nota_tabela_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='comentario',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
