# Generated by Django 5.2.10 on 2026-04-20 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0015_nota_comentario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
                ('nf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notas.nota')),
                ('usuario', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Comentário',
                'verbose_name_plural': 'Logs de Comentário',
            },
        ),
    ]
