# Generated by Django 5.2.10 on 2026-04-20 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0016_log_comentario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Custo2_OP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
                ('op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.op')),
                ('usuario', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico Custo 2 OP',
                'verbose_name_plural': 'Históricos Custo 2 OP',
            },
        ),
    ]
