# Generated by Django 5.2.10 on 2026-04-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0018_mesbloqueado_logbloqueiomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='custo_editado',
            field=models.BooleanField(default=False),
        ),
    ]
