# Generated by Django 5.2.10 on 2026-05-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0020_preferenciacolunasnota'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaGlobalColunasNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colunas_visiveis', models.JSONField(default=list)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Preferência Global de Colunas da Nota',
                'verbose_name_plural': 'Preferências Globais de Colunas das Notas',
            },
        ),
        migrations.DeleteModel(
            name='PreferenciaColunasNota',
        ),
    ]
