# Generated by Django 5.2.10 on 2026-05-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0021_preferenciaglobalcolunasnota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='base_icms',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18),
        ),
    ]
