# Generated by Django 5.2.10 on 2026-06-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0022_nota_base_icms'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='comissao',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18),
        ),
    ]
