# Generated by Django 5.2.10 on 2026-01-30 12:03

from django.db import migrations
from notas.models import CustomUser as User
from django.contrib.auth.hashers import make_password
from django.conf import settings

def criar_usuarios_padrao(apps, schema_editor):
    User.objects.bulk_create([
        User(
            is_superuser=True,
            is_active=True,
            is_staff=True,
            username=settings.USER_ADMIN,
            password=make_password(settings.PASS_ADMIN)
        ),
        User(
            username=settings.USER_SYSTEM,
            password=make_password(settings.PASS_SYSTEM)
        ),
    ])
    
class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(criar_usuarios_padrao)
    ]
