SELECT 
    SG.G1_FILIAL AS Filial, 
    SG.G1_COD AS Codigo,
    COD.B1_DESC AS DescCod,

    -- Lógica de grupo corrigido (nível 1)
    COD.B1_GPRODBI AS GrupoCorrigido,
    CASE 
        WHEN ISNULL(COD.B1_GPRODBI, '') = '' THEN COD.B1_GRUPO 
        ELSE COD.B1_GPRODBI 
    END AS GrupoFinal,
    CASE 
        WHEN ISNULL(COD.B1_GPRODBI, '') = '' THEN SBM.BM_DESC 
        ELSE SBM2.BM_DESC 
    END AS DescGrupo,

    SG.G1_COMP AS Componente,
    RTRIM(COMP.B1_DESC, ' ') +' - '+ SG.G1_COMP AS DescComp,
    COD.B1_UPRC AS PrecoCompraCOD,
    COMP.B1_UPRC AS PrecoCompraCOMP,
    SG.G1_QUANT AS Quantidade,
    SG.G1_INI AS Dt_INI,
    SG.G1_NIV AS Nivel,

    -- Nível 1
    SG.G1_COD AS CodigoNivel1,
    RTRIM(COD.B1_DESC, ' ') +' - '+ SG.G1_COD AS DescCodNivel1,
    SG.G1_INI AS Dt_ININivel1,
    
    -- Nível 2
    G2.G1_COMP AS CodigoNivel2,
    RTRIM(COD2.B1_DESC, ' ') +' - '+ G2.G1_COMP AS DescCodNivel2,
    G2.G1_INI AS Dt_ININivel2,
    
    -- Nível 3
    G3.G1_COMP AS CodigoNivel3,
    RTRIM(COD3.B1_DESC, ' ') +' - '+ G3.G1_COMP AS DescCodNivel3,
    G3.G1_INI AS Dt_ININivel3,

    -- Nível 4
    G4.G1_COMP AS CodigoNivel4,
    RTRIM(COD4.B1_DESC, ' ') +' - '+ G4.G1_COMP  AS DescCodNivel4,
    G4.G1_INI AS Dt_ININivel4,

    -- Nível 5
    G5.G1_COMP AS CodigoNivel5,
    RTRIM(COD5.B1_DESC, ' ') +' - '+ G5.G1_COMP AS DescCodNivel5,
    G5.G1_INI AS Dt_ININivel5,

    -- Nível 6
    G6.G1_COMP AS CodigoNivel6,
    RTRIM(COD6.B1_DESC, ' ') +' - '+ G6.G1_COMP AS DescCodNivel6,
    G6.G1_INI AS Dt_ININivel6,

    -- Soma do preço de compra dos componentes tipo MP
    ISNULL(CASE WHEN COMP.B1_TIPO IN ('MP','MC') THEN COMP.B1_UPRC ELSE 0 END, 0) +
    ISNULL(CASE WHEN COD2.B1_TIPO IN ('MP','MC') AND COD2.B1_QB <> '1' THEN COD2.B1_UPRC ELSE 0 END, 0) +
    ISNULL(CASE WHEN COD3.B1_TIPO IN ('MP','MC') THEN COD3.B1_UPRC ELSE 0 END, 0) +
    ISNULL(CASE WHEN COD4.B1_TIPO IN ('MP','MC') THEN COD4.B1_UPRC ELSE 0 END, 0) +
    ISNULL(CASE WHEN COD5.B1_TIPO IN ('MP','MC') THEN COD5.B1_UPRC ELSE 0 END, 0) +
    ISNULL(CASE WHEN COD6.B1_TIPO IN ('MP','MC') THEN COD6.B1_UPRC ELSE 0 END, 0) 
    AS SomaPrecoCompraMP,

    -- Soma da quantidade dos componentes tipo MP
    ISNULL(CASE WHEN COMP.B1_TIPO IN ('MP','MC') THEN SG.G1_QUANT ELSE 0 END, 0) +
    ISNULL(CASE WHEN COD2.B1_TIPO IN ('MP','MC') THEN G2.G1_QUANT ELSE 0 END, 0) +
    ISNULL(CASE WHEN COD3.B1_TIPO IN ('MP','MC') THEN G3.G1_QUANT ELSE 0 END, 0) +
    ISNULL(CASE WHEN COD4.B1_TIPO IN ('MP','MC') THEN G4.G1_QUANT ELSE 0 END, 0) +
    ISNULL(CASE WHEN COD5.B1_TIPO IN ('MP','MC') THEN G5.G1_QUANT ELSE 0 END, 0) +
    ISNULL(CASE WHEN COD6.B1_TIPO IN ('MP','MC') THEN G6.G1_QUANT ELSE 0 END, 0)
    AS SomaQuantidadeMP

FROM SG1010 AS SG

-- Nível 1
LEFT JOIN SB1010 AS COD ON COD.B1_COD = SG.G1_COD
    AND SUBSTRING(SG.G1_FILIAL, 1,2) = COD.B1_FILIAL
    AND COD.D_E_L_E_T_ <> '*'

LEFT JOIN SB1010 AS COMP ON COMP.B1_COD = SG.G1_COMP
    AND SUBSTRING(SG.G1_FILIAL, 1,2) = COMP.B1_FILIAL
    AND COMP.D_E_L_E_T_ <> '*'

LEFT JOIN SBM010 AS SBM ON COD.B1_GRUPO = SBM.BM_GRUPO
    AND BM_FILIAL = ' '
    AND SBM.D_E_L_E_T_ <> '*'

-- Novo JOIN para grupo alternativo
LEFT JOIN SBM010 AS SBM2 ON COD.B1_GPRODBI = SBM2.BM_GRUPO
    AND SBM2.BM_FILIAL = ' '
    AND SBM2.D_E_L_E_T_ <> '*'

-- Nível 2
LEFT JOIN SG1010 AS G2 ON G2.G1_COD = SG.G1_COMP
    AND G2.D_E_L_E_T_ <> '*'
LEFT JOIN SB1010 AS COD2 ON COD2.B1_COD = G2.G1_COMP
    AND SUBSTRING(G2.G1_FILIAL, 1,2) = COD2.B1_FILIAL
    AND COD2.D_E_L_E_T_ <> '*'

-- Nível 3
LEFT JOIN SG1010 AS G3 ON G3.G1_COD = G2.G1_COMP
    AND G3.D_E_L_E_T_ <> '*'
LEFT JOIN SB1010 AS COD3 ON COD3.B1_COD = G3.G1_COMP
    AND SUBSTRING(G3.G1_FILIAL, 1,2) = COD3.B1_FILIAL
    AND COD3.D_E_L_E_T_ <> '*'

-- Nível 4
LEFT JOIN SG1010 AS G4 ON G4.G1_COD = G3.G1_COMP
    AND G4.D_E_L_E_T_ <> '*'
LEFT JOIN SB1010 AS COD4 ON COD4.B1_COD = G4.G1_COMP
    AND SUBSTRING(G4.G1_FILIAL, 1,2) = COD4.B1_FILIAL
    AND COD4.D_E_L_E_T_ <> '*'

-- Nível 5
LEFT JOIN SG1010 AS G5 ON G5.G1_COD = G4.G1_COMP
    AND G5.D_E_L_E_T_ <> '*'
LEFT JOIN SB1010 AS COD5 ON COD5.B1_COD = G5.G1_COMP
    AND SUBSTRING(G5.G1_FILIAL, 1,2) = COD5.B1_FILIAL
    AND COD5.D_E_L_E_T_ <> '*'

-- Nível 6
LEFT JOIN SG1010 AS G6 ON G6.G1_COD = G5.G1_COMP
    AND G6.D_E_L_E_T_ <> '*'
LEFT JOIN SB1010 AS COD6 ON COD6.B1_COD = G6.G1_COMP
    AND SUBSTRING(G6.G1_FILIAL, 1,2) = COD6.B1_FILIAL
    AND COD6.D_E_L_E_T_ <> '*'

WHERE SG.D_E_L_E_T_ <> '*'
AND SG.G1_FILIAL = '0101'
--AND SG.G1_COD = 'G0010019'
--AND G3.G1_COMP = 'CH000004'
--AND  G2.G1_COMP= 'B00099GA'
AND TRIM(COD.B1_COD) = 'G0130091'
ORDER BY 8